extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-rust
  container: rust
pipelines:
  pullRequest:
    build:
      steps:
      - sh: rustup override set nightly
        name: rustup
      - sh: cargo install --path . --root ./apps --force -j 4
        name: cargo-install
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: rustup override set nightly
        name: rustup
      - sh: cargo install --path . --root ./apps --force -j 4
        name: cargo-install
